### PR TITLE
golang dapp 交互

### PR DESCRIPTION
**Pull request by rzry**
两个简单的示例,go 于类ETH链 dapp 交互.

### CODE REVIEW

**Review by qizhou — APPROVED** [review]

**Comment by maroonstar** [comment]
Thanks for PR!
There are some suggestions:
1. please change doc file from html to Markdown, all your docs are html, and have lots of style code in them.
2. image files too many. our repo is getting larger and larger, we are try to reduce the use of image file now , code and log could write in markdown

**Comment by rzry** [comment]
document  is org，image I will decrease  thanks

**Comment by rzry** [comment]
org can be rendered

**Comment by maroonstar** [comment]
Please join our discord channel~

**Pull request closed without merging**
