### PR TITLE
Add foundry script usage

### PR DESCRIPTION
**Pull request by oneforalone**
update some new demos for foundry

### CODE REVIEW

**Comment by liberhe** [comment]
> update some new demos for foundry

please add more description in readme.   It is recommened that take to Optimize the existing tasks rather than add link

**Review by 0x-stan — APPROVED** [review]

**Review by yingjingyang — APPROVED** [review]

**Review by liberhe — COMMENTED** [review]
It seems that https://github.com/leeduckgo/secp256k1-example-rs is a private repo using Elixir. Does it really need to load this lib

**Comment by oneforalone** [comment]
> It seems that https://github.com/leeduckgo/secp256k1-example-rs is a private repo using Elixir. Does it really need to load this lib

Nope, I'm quite sure that i did not add https://github.com/leeduckgo/secp256k1-example-rs to submodule, and i have no idea why it shows in my commit. Maybe it's a merge from others.

**Comment by oneforalone** [comment]
After checking, I believe that https://github.com/leeduckgo/secp256k1-example-rs is add by @leeduckgo 16 months ago , and i re-format it accidentally when i modifying the submodule file after syncing with the main branch. Therefore,  it's not relevant with this pull request. @leeduckgo Please check it out. And if the submodule it's not needed, please leave a comment and i'll delete it.
image

**Comment by liberhe** [comment]
> After checking, I believe that https://github.com/leeduckgo/secp256k1-example-rs is add by @leeduckgo 16 months ago with PR #177 , and i re-format it accidentally when i modifying the submodule file after syncing with the main branch. Therefore, it's not relevant with this pull request. @leeduckgo Please check it out. And if the submodule it's not needed, please leave a comment and i'll delete it.

all right, pls delete it directly. Thanks again for your contribution.

**Comment by liberhe** [comment]
> Okay, done.

add yanyanho666 to join our group

**Comment by oneforalone** [comment]
> > Okay, done.
> 
> add yanyanho666 to join our group

got it.

**Review by liberhe — APPROVED** [review]

**Review by 0x-stan — APPROVED** [review]

**Pull request merged**
