### PR TITLE
Update develop-tools.md

### PR DESCRIPTION
**Pull request by yilugit**
add remix online IDE URL

### CODE REVIEW

**Review by maroonstar — CHANGES_REQUESTED** [review]
Could you add more content please?

**Comment by yilugit** [comment]
sure, I will add more content in this pr

**Comment by liberhe** [comment]
> sure, I will add more content in this pr

Thanks for your contribution, you can also fix our English readme.

**Comment by yilugit** [comment]
I will close it and send another pr.

**Pull request closed without merging**
